name: Deploy to dev-green

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev-green
    concurrency: dev-green
    env:
      AWS_REGION: us-east-1
      ELASTICBEANSTALK_APPLICATION_NAME: screens
      ELASTICBEANSTALK_ENVIRONMENT_NAME: screens-dev-green

    steps:
      - uses: actions/checkout@v2
      - id: metadata
        uses: mbta/actions/commit-metadata@v1
      - uses: mbta/actions/build-push-ecr@v1
        id: build-push
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
      - name: Upload source map
        run: bash upload_assets.sh ${{ steps.build-push.outputs.docker-tag }}
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - id: deployment-package
        uses: mbta/actions/eb-ecr-dockerrun@v1
        with:
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
      - name: Deploy to EB
        uses: mbta/beanstalk-deploy@v18
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application-name: ${{ env.ELASTICBEANSTALK_APPLICATION_NAME }}
          environment-name: ${{ env.ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          version-label: ${{ steps.metadata.outputs.sha-short }}
          version-description: ${{ steps.metadata.outputs.commit-message }}
          region: ${{ env.AWS_REGION }}
          deployment-package: ${{ steps.deployment-package.outputs.deployment-package }}
          use-existing-version-if-available: true
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
